Repository microsoft/TypeScript-Website, pull requests merged in 2020-12, with the labels that each got.

#1352 [Translation into ja] Feature/translation nightly build into ja
  packages/documentation/copy/ja/Nightly Builds.md
Labels: jp, translation

#1385 [PT-BR] Errors.ts
  packages/playground-examples/copy/pt/JavaScript/Helping with JavaScript/Errors.ts
Labels: pt, translation

#1304 (zh) Add project options
  packages/tsconfig-reference/copy/zh/categories/Basic_Options_6172.md
  packages/tsconfig-reference/copy/zh/options/allowJs.md
  packages/tsconfig-reference/copy/zh/options/checkJs.md
  packages/tsconfig-reference/copy/zh/options/composite.md
  packages/tsconfig-reference/copy/zh/options/declaration.md
  packages/tsconfig-reference/copy/zh/options/downlevelIteration.md
  packages/tsconfig-reference/copy/zh/options/importHelpers.md
  packages/tsconfig-reference/copy/zh/options/incremental.md
  packages/tsconfig-reference/copy/zh/options/isolatedModules.md
  packages/tsconfig-reference/copy/zh/options/jsx.md
  packages/tsconfig-reference/copy/zh/options/lib.md
  packages/tsconfig-reference/copy/zh/options/module.md
  packages/tsconfig-reference/copy/zh/options/noEmit.md
  packages/tsconfig-reference/copy/zh/options/outDir.md
  packages/tsconfig-reference/copy/zh/options/outFile.md
  packages/tsconfig-reference/copy/zh/options/plugins.md
  packages/tsconfig-reference/copy/zh/options/removeComments.md
  packages/tsconfig-reference/copy/zh/options/rootDir.md
  packages/tsconfig-reference/copy/zh/options/sourceMap.md
  packages/tsconfig-reference/copy/zh/options/target.md
  packages/tsconfig-reference/copy/zh/options/tsBuildInfoFile.md
Labels: translation, zh

#1369 [ja translation] playground-example/3-8,3-9
  packages/playground-examples/copy/ja/3-7/Types and Code Flow/Assertion Functions.ts
  packages/playground-examples/copy/ja/3-7/Types and Code Flow/Recursive Type References.ts
  packages/playground-examples/copy/ja/3-7/Types and Code Flow/Uncalled Function Checks.ts
  packages/playground-examples/copy/ja/3-8/JSDoc Improvements/Accessibility Modifiers.js
  packages/playground-examples/copy/ja/3-8/Syntax and Messaging/Export Modules From.ts
  packages/playground-examples/copy/ja/3-8/Syntax and Messaging/Private Class Fields.ts
  packages/playground-examples/copy/ja/3-8/Syntax and Messaging/Type Imports.tsx
Labels: jp, translation

#1396 Translate documentation files (PT-BR): Utility Types / Variable Declarations
  packages/documentation/copy/pt/reference/Utility Types.md
  packages/documentation/copy/pt/reference/Variable Declarations.md
Labels: pt, translation

#1417 General error fixes
  packages/documentation/copy/pt/reference/Utility Types.md
  packages/documentation/copy/pt/reference/Variable Declarations.md
  packages/playground-examples/copy/pt/TypeScript/Language Extensions/Types vs Interfaces.ts
  packages/playground-examples/copy/pt/TypeScript/Language/Soundness.ts
  packages/playground-examples/copy/pt/TypeScript/Language/Structural Typing.ts
  packages/playground-examples/copy/pt/TypeScript/Language/Type Guards.ts
  packages/playground-examples/copy/pt/TypeScript/Language/Type Widening and Narrowing.ts
  packages/playground-examples/copy/pt/TypeScript/Primitives/Literals.ts
Labels: pt, translation

#1384 [PT-BR] Translating JSDoc Reference, Configuring Watch, Project References and Declaration Merging
  packages/documentation/copy/pt/javascript/Creating DTS files From JS.md
  packages/documentation/copy/pt/javascript/JSDoc Reference.md
  packages/documentation/copy/pt/project-config/Configuring Watch.md
  packages/documentation/copy/pt/project-config/Project References.md
  packages/documentation/copy/pt/reference/Declaration Merging.md
Labels: pt, translation

#1418 Typos
  packages/documentation/copy/pt/project-config/tsconfig.json.md
Labels: pt, translation

#1372 [PT-BR] <See in JSDoc.ts, Intro to Template Literals.ts, Mapped Types with Template Literals.ts, String Manipulation with Template Literals.ts>
  packages/playground-examples/copy/pt/4-1/New JS Features/See in JSDoc.ts
  packages/playground-examples/copy/pt/4-1/Template Literals/Intro to Template Literals.ts
  packages/playground-examples/copy/pt/4-1/Template Literals/Mapped Types with Template Literals.ts
  packages/playground-examples/copy/pt/4-1/Template Literals/String Manipulation with Template Literals.ts
Labels: pt, translation

#1345 translate 3 files into ko
  packages/documentation/copy/ko/reference/Declaration Merging.md
  packages/documentation/copy/ko/reference/Symbols.md
  packages/documentation/copy/ko/reference/Triple-Slash Directives.md
  packages/documentation/copy/ko/reference/Utility Types.md
  packages/tsconfig-reference/copy/ko/options/declaration.md
Labels: ko, translation

#1410 Translation 1 file to Ko: Private Class Fields
  packages/playground-examples/copy/ko/3-8/Syntax and Messaging/Private Class Fields.ts
Labels: ko, translation

#1338 docs(i18n-id): translate extends.md to forceConsistentCasingInFileNames.md and several config section into Indonesia
  packages/tsconfig-reference/copy/id/options/extends.md
  packages/tsconfig-reference/copy/id/options/fallbackPolling.md
  packages/tsconfig-reference/copy/id/options/files.md
  packages/tsconfig-reference/copy/id/options/forceConsistentCasingInFileNames.md
Labels: id, translation

#1434 docs(es) options section files were translated
  packages/tsconfig-reference/copy/es/options/charset.md
  packages/tsconfig-reference/copy/es/options/checkJs.md
  packages/tsconfig-reference/copy/es/options/composite.md
  packages/tsconfig-reference/copy/es/options/declaration.md
  packages/tsconfig-reference/copy/es/options/declarationDir.md
  packages/tsconfig-reference/copy/es/options/declarationMap.md
  packages/tsconfig-reference/copy/es/options/diagnostics.md
Labels: es, translation

#1354 translate 2 files into ko
  packages/documentation/copy/ko/reference/JSX.md
  packages/tsconfig-reference/copy/ko/options/jsxFragmentFactory.md
Labels: ko, translation

#1383 Translation 2 files into korean <Type Inference.md and JavaScript Playgrounds.js>
  packages/documentation/copy/ko/reference/Type Inference.md
  packages/playground-examples/copy/ko/Playground/Config/JavaScript Playgrounds.js
Labels: ko, translation

#1445 docs(i18n-id): Provide Indonesian translation for section `Modern JavaScript`
  packages/playground-examples/copy/id/JavaScript/Modern JavaScript/Async Await.ts
  packages/playground-examples/copy/id/JavaScript/Modern JavaScript/Immutability.ts
  packages/playground-examples/copy/id/JavaScript/Modern JavaScript/Import Export.ts
  packages/playground-examples/copy/id/JavaScript/Modern JavaScript/JSDoc Support.js
Labels: id, translation

#1452 [PL] translated dt.ts, head-seo.ts, playground.ts
  packages/typescriptlang-org/src/copy/pl.ts
  packages/typescriptlang-org/src/copy/pl/dt.ts
  packages/typescriptlang-org/src/copy/pl/head-seo.ts
  packages/typescriptlang-org/src/copy/pl/playground.ts
Labels: pl, translation
