Repository microsoft/TypeScript-Website, pull requests merged in 2020-11, with the labels that each got.

#1310 Polish translation for community.ts and documentation.ts
  packages/typescriptlang-org/src/copy/pl/community.ts
  packages/typescriptlang-org/src/copy/pl/documentation.ts
Labels: pl, translation

#1263 [PT-BR] Modules.md
  packages/documentation/copy/pt/reference/Modules.md
Labels: pt, translation

#1260 docs(i18n-id): Provide Indonesian translation for documentation
  packages/documentation/copy/id/Nightly Builds.md
  packages/documentation/copy/id/javascript/Creating DTS files From JS.md
  packages/documentation/copy/id/javascript/Intro to JS with TS.md
  packages/documentation/copy/id/javascript/JSDoc Reference.md
  packages/documentation/copy/id/project-config/Configuring Watch.md
  packages/documentation/copy/id/reference/Decorators.md
  packages/documentation/copy/id/reference/Iterators and Generators.md
  packages/documentation/copy/id/reference/JSX.md
  packages/documentation/copy/id/reference/Mixins.md
  packages/documentation/copy/id/reference/Symbols.md
  packages/documentation/copy/id/tutorials/Babel with TypeScript.md
  packages/documentation/copy/id/tutorials/DOM Manipulation.md
  packages/documentation/copy/id/tutorials/React.md
  packages/documentation/copy/id/tutorials/TypeScript Tooling in 5 minutes.md
Labels: id, translation

#1177 docs(i8n-id): Add Indonesian translation for rootDirs.md to skipLibCh…
  packages/tsconfig-reference/copy/id/options/rootDirs.md
  packages/tsconfig-reference/copy/id/options/skipDefaultLibCheck.md
  packages/tsconfig-reference/copy/id/options/skipLibCheck.md
Labels: id, translation

#1299 translate 1 file into ko: unknown and never
  packages/playground-examples/copy/ko/TypeScript/Primitives/Unknown and Never.ts
Labels: ko, translation

#1334 [PL] First handbook translations
  packages/documentation/copy/pl/handbook-v1/The Handbook.md
  packages/typescriptlang-org/src/copy/pl.ts
  packages/typescriptlang-org/src/copy/pl/handbook.ts
Labels: pl, translation

#1333 [PT-BR] bundledPackageName.md
  packages/tsconfig-reference/copy/pt/options/bundledPackageName.md
Labels: pt, translation

#1343 translate 3 files to korean
  packages/tsconfig-reference/copy/ko/options/exclude.md
  packages/tsconfig-reference/copy/ko/options/include.md
  packages/tsconfig-reference/copy/ko/options/lib.md
Labels: ko, translation

#1351 [Translation into ja] fix typo: Defenitely -> Definitely
  packages/typescriptlang-org/src/copy/ja/community.ts
Labels: jp, translation

#1344 Add translation to PT-BR
  packages/documentation/copy/pt/reference/Iterators and Generators.md
Labels: pt, translation

#1159 [PT-BR] DOM Manipulation.md file translation in the docs section
  packages/documentation/copy/pt/tutorials/DOM Manipulation.md
Labels: pt, translation

#1350 [PT-BR] [jsxImportSource.md, noUncheckedIndexedAccess.md]
  packages/tsconfig-reference/copy/pt/options/jsxImportSource.md
  packages/tsconfig-reference/copy/pt/options/noUncheckedIndexedAccess.md
Labels: pt, translation

#1367 [PT-BR] new JSX Support.ts
  packages/playground-examples/copy/pt/4-1/New JSX Support.ts
Labels: pt, translation
