Repository microsoft/TypeScript-Website, pull requests merged in 2020-09, with the labels that each got.

#999 [PT-BR] Optional Chaining.ts, Assertion Functions.ts, Recursive Type References.ts
  packages/playground-examples/copy/pt/3-7/Syntax and Messaging/Optional Chaining.ts
  packages/playground-examples/copy/pt/3-7/Types and Code Flow/Assertion Functions.ts
  packages/playground-examples/copy/pt/3-7/Types and Code Flow/Recursive Type References.ts
Labels: pt, translation

#992 add translation on file allowJs.md and allowSyntheticDefaultImports.md into indonesian
  packages/tsconfig-reference/copy/id/options/allowJs.md
  packages/tsconfig-reference/copy/id/options/allowSyntheticDefaultImports.md
Labels: id, translation

#988 docs(tsconfig-reference): translate in folder sections
  packages/tsconfig-reference/copy/id/sections/compilerOptions.md
  packages/tsconfig-reference/copy/id/sections/top_level.md
  packages/tsconfig-reference/copy/id/sections/watchOptions.md
Labels: translation

#1055 [PT-BR] This.ts
  packages/playground-examples/copy/pt/JavaScript/Working With Classes/This.ts
Labels: pt, translation

#1054 [PT-BR] Quick Fixes.ts, Fixits.ts and Mobile Support.ts
  packages/playground-examples/copy/pt/JavaScript/Helping with JavaScript/Quick Fixes.ts
  packages/playground-examples/copy/pt/Playground/Language/Fixits.ts
  packages/playground-examples/copy/pt/Playground/Tooling/Mobile Support.ts
Labels: pt, translation

#1057 [PT-BR] Classes 101.ts
  packages/playground-examples/copy/pt/JavaScript/Working With Classes/Classes 101.ts
Labels: pt, translation

#1060 Translation(PT-BR): Nullable Types.ts
  packages/playground-examples/copy/pt/TypeScript/Type Primitives/Nullable Types.ts
Labels: pt, translation

#1061 [PT-BR] Private Class Fields.ts
  packages/playground-examples/copy/pt/3-8/Syntax and Messaging/Private Class Fields.ts
Labels: pt, translation

#1056 Translating Checking Unions with Index Signature.ts to pt-br
  packages/playground-examples/copy/pt/3-8/Breaking Changes/Checking Unions with Index Signatures.ts
Labels: pt, translation

#1058 Translating Mixins.ts to pt-br
  packages/playground-examples/copy/pt/JavaScript/Working With Classes/Mixins.ts
Labels: pt, translation

#1066 Translate "Typing Functions.ts" to Portuguese
  packages/playground-examples/copy/pt/JavaScript/Functions with JavaScript/Typing Functions.ts
Labels: p, translation

#1040 Translation 3 files to Ko
  packages/documentation/copy/ko/tutorials/Babel with TypeScript.md
  packages/documentation/copy/ko/tutorials/React.md
  packages/documentation/copy/ko/tutorials/TypeScript Tooling in 5 minutes.md
Labels: translation

#976 translate paths to ko
  packages/tsconfig-reference/copy/ko/options/paths.md
Labels: translation

#1042 [translate-id] file allowUmdGlobalAccess.md until composite.md into indonesian
  packages/tsconfig-reference/copy/id/options/allowUmdGlobalAccess.md
  packages/tsconfig-reference/copy/id/options/allowUnreachableCode.md
  packages/tsconfig-reference/copy/id/options/allowUnusedLabels.md
  packages/tsconfig-reference/copy/id/options/alwaysStrict.md
  packages/tsconfig-reference/copy/id/options/assumeChangesOnlyAffectDirectDependencies.md
  packages/tsconfig-reference/copy/id/options/baseUrl.md
  packages/tsconfig-reference/copy/id/options/charset.md
  packages/tsconfig-reference/copy/id/options/checkJs.md
  packages/tsconfig-reference/copy/id/options/composite.md
Labels: translation

#1091 docs(translation): Add Indonesian translation for 3.7 fixits section
  packages/playground-examples/copy/id/3-7/Fixits/Big number literals.ts
  packages/playground-examples/copy/id/3-7/Fixits/Const to let.ts
  packages/playground-examples/copy/id/3-7/Fixits/Infer From Usage Changes.ts
  packages/playground-examples/copy/id/sections.json
Labels: id, translation

#984 [Translate] translate head-seo, community and documentation to ja
  packages/typescriptlang-org/src/copy/ja.ts
  packages/typescriptlang-org/src/copy/ja/community.ts
  packages/typescriptlang-org/src/copy/ja/documentation.ts
  packages/typescriptlang-org/src/copy/ja/head-seo.ts
Labels: translation

#961 [translate]meta types to ja
  packages/playground-examples/copy/ja/TypeScript/Meta-Types/Conditional Types.ts
  packages/playground-examples/copy/ja/TypeScript/Meta-Types/Discriminate Types.ts
  packages/playground-examples/copy/ja/TypeScript/Meta-Types/Indexed Types.ts
  packages/playground-examples/copy/ja/TypeScript/Meta-Types/Mapped Types.ts
Labels: translation

#1087 [PT-BR] Nominal Typing and Meta-Types
  packages/playground-examples/copy/pt/TypeScript/Language Extensions/Nominal Typing.ts
  packages/playground-examples/copy/pt/TypeScript/Meta-Types/Discriminate Types.ts
  packages/playground-examples/copy/pt/TypeScript/Meta-Types/Indexed Types.ts
  packages/playground-examples/copy/pt/TypeScript/Meta-Types/Mapped Types.ts
Labels: pt, translation

#1064 [PT-BR] Namespaces, Symbols
  packages/documentation/copy/pt/reference/Namespaces.md
  packages/documentation/copy/pt/reference/Symbols.md
Labels: translation

#1070 [PT-BR] Decorators.md
  packages/documentation/copy/pt/reference/Decorators.md
Labels: translation

#1074 [PT-BR] Sharable URLs.ts, TypeScript Versions.ts
  packages/playground-examples/copy/pt/Playground/Tooling/Sharable URLs.ts
  packages/playground-examples/copy/pt/Playground/Tooling/TypeScript Versions.ts
Labels: pt, translation

#1080 [PT-BR] Translating playground-examples files
  packages/playground-examples/copy/pt/JavaScript/External APIs/TypeScript with Deno.ts
  packages/playground-examples/copy/pt/JavaScript/External APIs/TypeScript with Node.js
  packages/playground-examples/copy/pt/JavaScript/External APIs/TypeScript with React.tsx
  packages/playground-examples/copy/pt/JavaScript/External APIs/TypeScript with Web.js
  packages/playground-examples/copy/pt/JavaScript/External APIs/TypeScript with WebGL.js
Labels: pt, translation

#1084 [PT-BR] Translation of some playground example files
  packages/playground-examples/copy/pt/3-7/Syntax and Messaging/Nullish Coalescing.ts
Labels: pt, translation

#1082 Translate 3 playground-examples files to ko
  packages/playground-examples/copy/ko/3-7/Fixits/Const to let.ts
  packages/playground-examples/copy/ko/3-8/Syntax and Messaging/Export Modules From.ts
  packages/playground-examples/copy/ko/3-8/Syntax and Messaging/Type Imports.tsx
  packages/playground-examples/copy/ko/sections.json
Labels: ko, translation

#1112 docs(translation): Add Indonesian translation for TS 3.7 Syntax and Messaging section
  packages/playground-examples/copy/id/3-7/Syntax And Messaging/Flattened Error Reporting.ts
  packages/playground-examples/copy/id/3-7/Syntax And Messaging/Nullish Coalescing.ts
  packages/playground-examples/copy/id/3-7/Syntax And Messaging/Optional Chaining.ts
Labels: id, translation

#1076 Translation 2 files to Ko
  packages/playground-examples/copy/ko/3-7/Fixits/Big number literals.ts
  packages/playground-examples/copy/ko/sections.json
  packages/tsconfig-reference/copy/ko/options/newLine.md
Labels: ko, translation

#1077 translate Async Await.ts, Optional Chaining.ts to ko
  packages/playground-examples/copy/ko/3-7/Syntax and Messaging/Optional Chaining.ts
  packages/playground-examples/copy/ko/JavaScript/Modern JavaScript/Async Await.ts
  packages/playground-examples/copy/ko/sections.json
Labels: ko, translation

#1114 Translate Source Maps and Strict Checks to ko
  packages/tsconfig-reference/copy/ko/categories/Source_Map_Options_6175.md
  packages/tsconfig-reference/copy/ko/categories/Strict_Type_Checking_Options_6173.md
Labels: ko, translation

#1075 [PT-BR] Javascript Playgrounds.js, New Compiler Defaults.ts, Automatic Type Acquisition.js
  packages/playground-examples/copy/pt/Playground/Config/JavaScript Playgrounds.js
  packages/playground-examples/copy/pt/Playground/Config/New Compiler Defaults.ts
  packages/playground-examples/copy/pt/Playground/Language/Automatic Type Acquisition.ts
Labels: pt, translation

#1097 [PT-BR] Translate Async Await and Immutability
  packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Async Await.ts
  packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Immutability.ts
Labels: pt, translation

#1021 [pt-BR] SkiptDefaultLib, SkipLib, SourceMap and SourceRoot
  packages/tsconfig-reference/copy/pt/options/skipDefaultLibCheck.md
  packages/tsconfig-reference/copy/pt/options/skipLibCheck.md
  packages/tsconfig-reference/copy/pt/options/sourceMap.md
  packages/tsconfig-reference/copy/pt/options/sourceRoot.md
Labels: translation

#1065 Translate "Generic Functions.ts" to Portuguese
  packages/playground-examples/copy/pt/JavaScript/Functions with JavaScript/Generic Functions.ts
Labels: pt, translation

#1072 [PT-BR] tsconfig.json.md
  packages/documentation/copy/pt/project-config/tsconfig.json.md
Labels: translation

#1081 Translation 2 files to Ko
  packages/playground-examples/copy/ko/TypeScript/Language Extensions/Enums.ts
  packages/playground-examples/copy/ko/TypeScript/Language Extensions/Types vs Interfaces.ts
  packages/playground-examples/copy/ko/sections.json
Labels: ko, translation

#1147 docs(i18n-id): translate declaration.md and several config section into Indonesia
  packages/tsconfig-reference/copy/id/options/declaration.md
Labels: id, translation

#1142 docs(i18n-id): translate declarationDir.md and several config section into Indonesia
  packages/tsconfig-reference/copy/id/options/declarationDir.md
Labels: id, translation

#1154 docs(i18n-id): translate declarationMap.md, diagnostics.md, and several config section into Indonesia
  packages/tsconfig-reference/copy/id/options/declarationMap.md
  packages/tsconfig-reference/copy/id/options/diagnostics.md
Labels: id, translation
