Repository microsoft/TypeScript-Website, pull requests merged in 2020-10, with the labels that each got.

#1186 docs(i18n-id): Provide Indonesian translation for section 3-8/Breaking Changes
  packages/playground-examples/copy/id/3-8/Breaking Changes/Checking Unions with Index Signatures.ts
Labels: id, translation

#1116 Translation 3 files to Ko
  packages/playground-examples/copy/ko/JavaScript/JavaScript Essentials/Hello World.ts
  packages/tsconfig-reference/copy/ko/options/baseUrl.md
  packages/tsconfig-reference/copy/ko/options/charset.md
Labels: ko, translation

#1151 translate 2 files into ko: any, literals
  packages/playground-examples/copy/ko/TypeScript/Primitives/Any.ts
  packages/playground-examples/copy/ko/TypeScript/Primitives/Literals.ts
Labels: ko, translation

#1197 docs(i18n-id): translate jsx, jsxFactory & jsxFragmentFactory into Indonesia
  packages/tsconfig-reference/copy/id/options/jsx.md
  packages/tsconfig-reference/copy/id/options/jsxFactory.md
  packages/tsconfig-reference/copy/id/options/jsxFragmentFactory.md
Labels: id, translation

#1201 docs(i18n-id): Provide Indonesian translation for JSDoc Improvement section
  packages/playground-examples/copy/id/3-8/JSDoc Improvements/Accessibility Modifiers.js
Labels: id, translation

#1171 docs(i18n-id): translate downlevelIteration.md and several config into Indonesia
  packages/tsconfig-reference/copy/id/options/downlevelIteration.md
Labels: id, translation

#1166 docs(i18n-id): translate disableSourceOfProjectReferenceRedirect.md and several config into Indonesia
  packages/tsconfig-reference/copy/id/options/disableSourceOfProjectReferenceRedirect.md
Labels: id, translation

#1181 I18n-id for Code Flow.ts, Functions.ts, Hello World.ts, Objects and …
  packages/playground-examples/copy/id/JavaScript/JavaScript Essentials/Code Flow.ts
  packages/playground-examples/copy/id/JavaScript/JavaScript Essentials/Functions.ts
  packages/playground-examples/copy/id/JavaScript/JavaScript Essentials/Hello World.ts
  packages/playground-examples/copy/id/JavaScript/JavaScript Essentials/Objects and Arrays.ts
Labels: id, translation

#1176 docs(i18n-id): translate from reactNamespace.md to rootDir.md into Indonesian
  packages/tsconfig-reference/copy/id/options/reactNamespace.md
  packages/tsconfig-reference/copy/id/options/references.md
  packages/tsconfig-reference/copy/id/options/removeComments.md
  packages/tsconfig-reference/copy/id/options/resolveJsonModule.md
  packages/tsconfig-reference/copy/id/options/rootDir.md
Labels: id, translation

#1198 docs(i18n-id): translate esModuleInterop.md and several config into Indonesia
  packages/tsconfig-reference/copy/id/options/esModuleInterop.md
Labels: id, translation

#1204 docs(i18n-id): Provide Indonesian translation for section 3-8/Syntax and Messaging
  packages/playground-examples/copy/id/3-8/Syntax and Messaging/Export Modules From.ts
  packages/playground-examples/copy/id/3-8/Syntax and Messaging/Private Class Fields.ts
  packages/playground-examples/copy/id/3-8/Syntax and Messaging/Type Imports.tsx
Labels: id, translation

#1175 docs(i18n-id): Add Indonesian translation for Types And Code Flow section
  packages/playground-examples/copy/id/3-7/Types and Code Flow/Assertion Functions.ts
  packages/playground-examples/copy/id/3-7/Types and Code Flow/Recursive Type Reference.ts
  packages/playground-examples/copy/id/3-7/Types and Code Flow/Uncalled Function Checks.ts
Labels: id, translation

#1109 [PT-BR] Babel with TypeScript.md
  packages/documentation/copy/pt/tutorials/Babel with TypeScript.md
Labels: pt, translation

#1179 [PT-BR] disableReferencedProjectLoad.md
  packages/tsconfig-reference/copy/pt/options/disableReferencedProjectLoad.md
Labels: pt, translation

#1122 [PT-BR] Import Export.ts, JSDoc Support.ts and Generic Classes.ts
  packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
  packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
  packages/playground-examples/copy/pt/JavaScript/Working With Classes/Generic Classes.ts
Labels: pt, translation

#1172 docs(i18n-id): translate emitBOM.md, emitDeclarationOnly.md and several config into Indonesia
  packages/tsconfig-reference/copy/id/options/emitBOM.md
  packages/tsconfig-reference/copy/id/options/emitDeclarationOnly.md
Labels: id, translation

#1214 docs(i18n-id): Provide Indonesian translation for two parts of section 4-0
  packages/playground-examples/copy/id/4-0/New Checks/Class Constructor Code Flow.ts
  packages/playground-examples/copy/id/4-0/New JS Features/JSDoc Deprecated.ts
  packages/playground-examples/copy/id/4-0/New JS Features/Logical Operators and Assignment.ts
  packages/playground-examples/copy/id/4-0/New JS Features/Nullish Coalescing.ts
Labels: id, translation

#1191 docs(i18n-id): translate emitDecoratorMetadata.md and several config into Indonesia
  packages/tsconfig-reference/copy/id/options/emitDecoratorMetadata.md
Labels: id, translation

#1228 docs(i18n-id): Provide Indonesian translation for section 4-0/New TS Features
  packages/playground-examples/copy/id/4-0/New TS Features/Named Tuples.ts
  packages/playground-examples/copy/id/4-0/New TS Features/Unknown in Catch.ts
  packages/playground-examples/copy/id/4-0/New TS Features/Variadic Tuples.ts
Labels: id, translation

#1227 fix: playground plugin link for zh translation
  packages/typescriptlang-org/src/copy/zh/playground.ts
Labels: translation, zh

#1174 Translate Functions and noImplicitAny to ko
  packages/playground-examples/copy/ko/JavaScript/JavaScript Essentials/Functions.ts
  packages/tsconfig-reference/copy/ko/options/noImplicitAny.md
Labels: ko, translation

#1156 translate 2 playground files to ko, update 2 playgound files(ko)
  packages/playground-examples/copy/ko/3-7/Syntax and Messaging/Optional Chaining.ts
  packages/playground-examples/copy/ko/JavaScript/External APIs/TypeScript with Node.js
  packages/playground-examples/copy/ko/JavaScript/External APIs/TypeScript with React.tsx
  packages/playground-examples/copy/ko/JavaScript/Modern JavaScript/Async Await.ts
Labels: ko, translation

#1173 docs(i18n-id): translate generateCpuProfile.md until isolatedModules.md into indonesian
  packages/tsconfig-reference/copy/id/options/generateCpuProfile.md
  packages/tsconfig-reference/copy/id/options/importHelpers.md
  packages/tsconfig-reference/copy/id/options/importsNotUsedAsValues.md
  packages/tsconfig-reference/copy/id/options/include.md
  packages/tsconfig-reference/copy/id/options/incremental.md
  packages/tsconfig-reference/copy/id/options/inlineSourceMap.md
  packages/tsconfig-reference/copy/id/options/inlineSources.md
  packages/tsconfig-reference/copy/id/options/isolatedModules.md
Labels: id, translation

#1229 docs(i18n-id): Translate out.md until outFile.md into indonesian
  packages/tsconfig-reference/copy/id/options/out.md
  packages/tsconfig-reference/copy/id/options/outDir.md
  packages/tsconfig-reference/copy/id/options/outFile.md
Labels: id, translation

#1238 docs(i18n-id): Provide Indonesian translation for section JavaScript/External APIs
  packages/playground-examples/copy/id/JavaScript/External APIs/TypeScript with Deno.ts
  packages/playground-examples/copy/id/JavaScript/External APIs/TypeScript with Node.js
  packages/playground-examples/copy/id/JavaScript/External APIs/TypeScript with React.tsx
  packages/playground-examples/copy/id/JavaScript/External APIs/TypeScript with Web.js
  packages/playground-examples/copy/id/JavaScript/External APIs/TypeScript with WebGL.js
Labels: id, translation

#1203 [PT-BR] Type Widening and Narrowing and Type Guards
  packages/playground-examples/copy/pt/Typescript/Language/Type Guards.ts
  packages/playground-examples/copy/pt/Typescript/Language/Type Widening and Narrowing.ts
Labels: pt, translation

#1195 Translation of Module Resolutions.md
  packages/documentation/copy/pt/reference/Module Resolution.md
Labels: pt, translation

#978 Translate 3 tsconfig files to ja
  packages/tsconfig-reference/copy/ja/categories/Watch_Options_999.md
  packages/tsconfig-reference/copy/ja/intro.md
  packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
Labels: translation

#1264 docs(i18n-id): translate experimental decorators and extended diagnostics to indonesia
  packages/tsconfig-reference/copy/id/options/experimentalDecorators.md
  packages/tsconfig-reference/copy/id/options/extendedDiagnostics.md
Labels: id, translation

#1224 Translation 2 files into ko: Immutability & Import Export
  packages/playground-examples/copy/ko/JavaScript/Modern JavaScript/Immutability.ts
  packages/playground-examples/copy/ko/JavaScript/Modern JavaScript/Import Export.ts
Labels: ko, translation

#1279 docs(i18n-id): translate watchFile.md and dt.ts to Indonesian
  packages/tsconfig-reference/copy/id/options/watchFile.md
  packages/typescriptlang-org/src/copy/id/dt.ts
  packages/typescriptlang-org/src/copy/id/index.ts
Labels: id, translation

#1268 Tsconfig zh
  packages/tsconfig-reference/copy/zh/categories/Module_Resolution_Options_6174.md
  packages/tsconfig-reference/copy/zh/options/allowSyntheticDefaultImports.md
  packages/tsconfig-reference/copy/zh/options/allowUmdGlobalAccess.md
  packages/tsconfig-reference/copy/zh/options/baseUrl.md
  packages/tsconfig-reference/copy/zh/options/esModuleInterop.md
  packages/tsconfig-reference/copy/zh/options/moduleResolution.md
  packages/tsconfig-reference/copy/zh/options/paths.md
  packages/tsconfig-reference/copy/zh/options/preserveSymlinks.md
  packages/tsconfig-reference/copy/zh/options/rootDirs.md
  packages/tsconfig-reference/copy/zh/options/typeRoots.md
  packages/tsconfig-reference/copy/zh/options/types.md
Labels: translation, zh

#1296 docs(i18n-id): translate exclude.md and several config section into Indonesia
  packages/tsconfig-reference/copy/id/options/exclude.md
Labels: id, translation

#1256 Translate documentation files (PT-BR): Type Inference / Type Compatibility
  packages/documentation/copy/pt/reference/Type Compatibility.md
  packages/documentation/copy/pt/reference/Type Inference.md
Labels: pt, translation

#1212 [PT-BR] Soundness.md
  packages/playground-examples/copy/pt/Typescript/Language/Soundness.ts
Labels: pt, translation

#1239 Translation of Triple-Slash Directives.md
  packages/documentation/copy/pt/reference/Triple-Slash Directives.md
Labels: pt, translation

#1280 [PT-BR] Namespaces and Modules
  packages/documentation/copy/pt/reference/Namespaces and Modules.md
Labels: pt, translation

#1281 docs(i18n-id): Provide Indonesian translation for section JavaScript/Functions With JavaScript
  packages/playground-examples/copy/id/JavaScript/Functions with JavaScript/Function Chaining.ts
  packages/playground-examples/copy/id/JavaScript/Functions with JavaScript/Generic Functions.ts
  packages/playground-examples/copy/id/JavaScript/Functions with JavaScript/Typing Functions.ts
Labels: id, translation

#1282 docs(i18n-id): Translate no implicits tsconfig option
  packages/tsconfig-reference/copy/id/options/noImplicitAny.md
  packages/tsconfig-reference/copy/id/options/noImplicitReturns.md
  packages/tsconfig-reference/copy/id/options/noImplicitThis.md
  packages/tsconfig-reference/copy/id/options/noImplicitUseStrict.md
Labels: id, translation

#1297 docs(i18n-id): translate target.md, types.md and watchDirectory.md to Indonesian
  packages/tsconfig-reference/copy/id/options/target.md
  packages/tsconfig-reference/copy/id/options/types.md
  packages/tsconfig-reference/copy/id/options/watchDirectory.md
Labels: id, translation
