Repository microsoft/TypeScript-Website, pull requests merged in 2021-01, with the labels that each got.

#1435 Translation 3 file to Ko: playground-examples/copy/4-0
  packages/playground-examples/copy/ko/4-0/New Checks/Class Constructor Code Flow.ts
  packages/playground-examples/copy/ko/4-0/New JS Features/JSDoc Deprecated.ts
  packages/playground-examples/copy/ko/4-0/New JS Features/Logical Operators and Assignment.ts
Labels: ko, translation

#1440 Translate 2 files to ko
  packages/tsconfig-reference/copy/ko/options/target.md
  packages/tsconfig-reference/copy/ko/options/traceResolution.md
Labels: ko, translation

#1397 [ja translation] playground-example/4-0
  packages/playground-examples/copy/ja/4-0/New Checks/Class Constructor Code Flow.ts
  packages/playground-examples/copy/ja/4-0/New JS Features/JSDoc Deprecated.ts
  packages/playground-examples/copy/ja/4-0/New JS Features/Logical Operators and Assignment.ts
  packages/playground-examples/copy/ja/4-0/New JS Features/Nullish Coalescing.ts
  packages/playground-examples/copy/ja/4-0/New TS Features/Named Tuples.ts
  packages/playground-examples/copy/ja/4-0/New TS Features/Unknown in Catch.ts
  packages/playground-examples/copy/ja/4-0/New TS Features/Variadic Tuples.ts
Labels: jp, translation

#1431 Translation of the Mixins.md file for ptbr, from the documents section
  packages/documentation/copy/pt/reference/Mixins.md
Labels: pt, translation

#1424 [PT-BR] Variadic Tuples.ts
  packages/playground-examples/copy/pt/4-0/New TS Features/Variadic Tuples.ts
Labels: pt, translation

#1426 translate 3 files to ko, update 2 files
  packages/documentation/copy/ko/reference/Iterators and Generators.md
  packages/playground-examples/copy/ko/JavaScript/External APIs/TypeScript with Node.js
  packages/playground-examples/copy/ko/JavaScript/External APIs/TypeScript with React.tsx
  packages/playground-examples/copy/ko/JavaScript/External APIs/TypeScript with Web.js
  packages/playground-examples/copy/ko/JavaScript/Functions with JavaScript/Generic Functions.ts
Labels: ko, translation

#1439 translate 2files into ko. (sourceRoot.md, strict.md)
  packages/tsconfig-reference/copy/ko/options/sourceRoot.md
  packages/tsconfig-reference/copy/ko/options/strict.md
Labels: ko, translation

#1422 [PT-BR] Translating Type Checking JavaScript Files
  packages/documentation/copy/pt/javascript/Type Checking JavaScript Files.md
Labels: pt, translation

#1421 [PT-BR] Translation of JSX.md file
  packages/documentation/copy/pt/reference/JSX.md
Labels: pt, translation

#1419 [ja translation] playground-example/4-1
  packages/playground-examples/copy/ja/4-1/New JS Features/New JSX Support.ts
  packages/playground-examples/copy/ja/4-1/New JS Features/See in JSDoc.ts
  packages/playground-examples/copy/ja/4-1/Template Literals/Intro to Template Literals.ts
  packages/playground-examples/copy/ja/4-1/Template Literals/Mapped Types with Template Literals.ts
  packages/playground-examples/copy/ja/4-1/Template Literals/String Manipulation with Template Literals.ts
Labels: jp, translation

#1458 i18n: add zh translation of "Nightly Builds"
  packages/documentation/copy/zh/Nightly Builds.md
Labels: translation, zh

#1478 [ja translation] TypeScript-Website/packages/documentation/copy/en/javascript/*.md
  packages/documentation/copy/ja/javascript/Creating DTS files From JS.md
  packages/documentation/copy/ja/javascript/Intro to JS with TS.md
  packages/documentation/copy/ja/javascript/JSDoc Reference.md
  packages/documentation/copy/ja/javascript/Type Checking JavaScript Files.md
Labels: jp, translation

#1432 [ja translation] tsconfig-reference 9 files
  packages/tsconfig-reference/copy/ja/options/disableReferencedProjectLoad.md
  packages/tsconfig-reference/copy/ja/options/jsxFragmentFactory.md
  packages/tsconfig-reference/copy/ja/options/jsxImportSource.md
  packages/tsconfig-reference/copy/ja/options/noUncheckedIndexedAccess.md
  packages/tsconfig-reference/copy/ja/options/watchDirectory.md
  packages/tsconfig-reference/copy/ja/options/watchFile.md
  packages/tsconfig-reference/copy/ja/sections/compilerOptions.md
  packages/tsconfig-reference/copy/ja/sections/top_level.md
  packages/tsconfig-reference/copy/ja/sections/watchOptions.md
Labels: jp, translation

#1295 Translate strict type checking options into zh
  packages/tsconfig-reference/copy/zh/categories/Strict_Type_Checking_Options_6173.md
  packages/tsconfig-reference/copy/zh/options/alwaysStrict.md
  packages/tsconfig-reference/copy/zh/options/noImplicitAny.md
  packages/tsconfig-reference/copy/zh/options/noImplicitThis.md
  packages/tsconfig-reference/copy/zh/options/strict.md
  packages/tsconfig-reference/copy/zh/options/strictBindCallApply.md
  packages/tsconfig-reference/copy/zh/options/strictFunctionTypes.md
  packages/tsconfig-reference/copy/zh/options/strictNullChecks.md
  packages/tsconfig-reference/copy/zh/options/strictPropertyInitialization.md
Labels: translation, zh

#1483 [PT-BR] translating 'dt.ts' file for ptbr, from the app section
  packages/typescriptlang-org/src/copy/pt/dt.ts
Labels: pt, translation

#1449 Translation 2 file to Ko
  packages/playground-examples/copy/ko/4-0/New JS Features/Nullish Coalescing.ts
  packages/playground-examples/copy/ko/4-0/New TS Features/Named Tuples.ts
Labels: ko, translation

#1504 Translate Nullish Coalescing to ko
  packages/playground-examples/copy/ko/3-7/Syntax and Messaging/Nullish Coalescing.ts
Labels: ko, translation

#1518 Translate 1 file to ko - Unknown in Catch
  packages/playground-examples/copy/ko/4-0/New TS Features/Unknown in Catch.ts
Labels: ko, translation

#1486 Translate 1 file to Ko - JSDoc Support.js
  packages/playground-examples/copy/ko/JavaScript/Modern JavaScript/JSDoc Support.js
Labels: ko, translation

#1455 Translate 1 file to Ko - This
  packages/playground-examples/copy/ko/JavaScript/Working With Classes/This.ts
Labels: ko, translation

#1531 Translate 1 file to Ko - Accessibility Modifiers
  packages/playground-examples/copy/ko/3-8/JSDoc Improvements/Accessibility Modifiers.js
Labels: ko, translation

#1511 Translate 1 file to ko - Uncalled Function Checks
  packages/playground-examples/copy/ko/3-7/Types and Code Flow/Uncalled Function Checks.ts
Labels: ko, translation
